name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on nightly
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
        - nightly

        features:
        - ''
        - '--no-default-features'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build unicode_names2
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose ${{ matrix.features }}

      - name: Test unicode_names2
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}

      - name: Bench unicode_names2
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --verbose ${{ matrix.features }}

      - name: Doc unicode_names2
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose ${{ matrix.features }}

      - name: cd unicode_names2_macros
        run: cd unicode_names2_macros/

      - name: Build unicode_names2_macros
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose ${{ matrix.features }}

      - name: Test unicode_names2_macros
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}

      - name: Doc unicode_names2_macros
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose ${{ matrix.features }}

      - name: cd generator
        run: cd ../generator/

      - name: Build generator
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose ${{ matrix.features }}

      - name: Test generator
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}

      - name: Doc generator
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose ${{ matrix.features }}

  build:
    # We cannot test on these versions, because tests and bench rely on
    # features that are still unstable.
    name: Build on non-nightly
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
        - stable
        - beta
        - 1.48.0

        features:
        - ''
        - '--no-default-features'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose ${{ matrix.features }}
